export const siteConfig = {
  name: 'Izzlan Anuar',
  title: 'Tech Support Engineer',
  description: 'Portfolio website of Izzlan Anuar',
  accentColor: '#1d4ed8',
  social: {
    email: 'eizlan09@gmail.com',
    linkedin: 'https://linkedin.com/in/muhammad-izzlan-917707200',
    github: 'https://github.com/beginnerIzz',
  },
  aboutMe:
    'I love solving problems, automate things and learn new technologies but among all I prefer travelling the world',
  skills: ['GCP', 'AWS', 'Azure', 'Python', 'Kubernetes', 'Docker', 'Linux', 'Incident Management', 'Observability', 'GitOps'],
  experience: [
    {
      company: 'BigPay',
      title: 'Tech Support Engineer',
      dateRange: 'April 2024 - Present',
      bullets: [
        '--- Support (Production & Incident Handling)',
        'Acted as first responder for production incidents across multiple environments, ensuring timely triage, mitigation, and escalation',
        'Diagnosed issues across APIs, backend services, and transaction flows using logs, metrics, and traces',
        'Collaborated closely with KYC, Ops, Customer Experience and Engineering teams to resolve customer-impacting issues and ensure service continuity',
        'Built automation scripts integrating with internal APIs to streamline operational processes and reduce manual intervention',
        '--- Infrastructure & Reliability',
        'Managed and supported cloud-native infrastructure on Google Cloud Platform (GCP), ensuring high availability and scalability of production systems',
        'Operated and troubleshooted microservices running on Kubernetes, including debugging pod failures, resource constraints, and networking issues',
        'Implemented and supported GitOps workflows using Flux, enabling automated and version-controlled deployments across environments',
        'Designed and maintained deployment configurations using Helm (Helm charts & templating), improving consistency and reusability of infrastructure manifests',
        'Performed and monitored canary deployments to safely roll out new features, minimizing risk and enabling quick rollback in case of failures',
        '--- Key Achievements & Impact',
        'Reduced incident resolution time by leveraging end-to-end observability (logs, metrics, traces)',
        'Improved system reliability and visibility across production environments',
        'Increased operational efficiency through automation of repetitive support tasks',
        'Strengthened cross-team collaboration between Support, Infrastructure, and Operations for faster issue resolution',
      ],
    },
    {
      company: 'AirAsia Move',
      title: 'L1/L2 Cloud Engineer',
      dateRange: 'Dec 2022 - April 2024',
      bullets: [
        '--- Monitoring & Incident Management',
        'Provided 24/7 monitoring across multiple business domains (Flight, Hotel, Ride, Food), ensuring service availability',
        'Performed incident triage using severity classification (P0–P3), triggering escalation and response workflows',
        'Acted as Incident Manager for P0/P1 incidents, coordinating stakeholders and leading war room sessions',
        'Delivered timely incident communications and status updates until resolution',
        '--- Cloud & System Operations',
        'Monitored systems across full stack layers (Infrastructure, Platform, Application) in Google Cloud Platform',
        'Investigated API and backend service issues within distributed systems environments',
        'Managed incident tracking and documentation using Jira and Confluence',
        'Maintained alert hygiene by tuning, acknowledging, and silencing alerts to reduce noise and improve signal quality',
        '--- Key Achievements & Impact',
        'Improved incident response efficiency through structured triage and escalation practices',
        'Reduced downtime by effectively coordinating cross-functional teams during critical incidents',
        'Increased monitoring effectiveness by optimizing alerting and reducing false positives',
      ],
    },
    {
      company: 'Huawei Inc',
      title: 'IT Cloud Engineer',
      dateRange: 'Dec 2021 - Dec 2022',
      bullets: [
        '--- Customer Support & Incident Handling',
        'Handled a wide range of technical inquiries related to cloud infrastructure, supporting enterprise customers across APAC',
        'Investigated and resolved complex incidents using log analysis, ensuring timely resolution within defined SLAs',
        'Collaborated with L2/L3 teams to troubleshoot high-severity and escalated issues',
        'Provided 24/7 support coverage, ensuring continuous service availability and customer satisfaction',
        '--- Cloud & Infrastructure Operations',
        'Supported cloud platforms based on OpenStack (FusionSphere CPS/OM), including compute, storage, and virtualization layers',
        'Performed deep-dive log analysis across distributed systems to identify system anomalies and performance bottlenecks',
        'Conducted regular system health checks on servers and storage systems to maintain operational stability',
        'Worked closely with Field Service Engineers (FSE) to troubleshoot hardware/software issues prior to upgrades and migrations',
        '--- Root Cause Analysis & Problem Management',
        'Produced detailed Root Cause Analysis (RCA) reports for incidents related to cloud, server, and storage systems',
        'Identified recurring issues and contributed to long-term fixes and preventive measures',
        'Improved issue resolution workflows by standardizing troubleshooting and documentation practices',
        '--- Technologies & Platforms',
        'Cloud: FusionSphere (OpenStack-based CPS/OM)',
        'Compute: Huawei TaiShan, E9000, Blade, Rack servers',
        'Storage: Huawei OceanStor, S3900, S2600',
        '--- Impact',
        'Maintained high SLA compliance across multi-region customer environments',
        'Reduced recurring incidents through effective RCA and collaboration with engineering teams',
        'Strengthened operational reliability via proactive health checks and issue prevention',
      ],
    },
  ],
  projects: [
    {
      name: 'Kubernetes Intro',
      description: 'Learning Kubernetes from scratch ',
      link: 'https://medium.com/@eizlan09/kubernetes-introduction-784e7c1724a4',
      skills: ['AWS', 'Docker', 'Kubernetes'],
    },
  ],
  education: [
    {
      school: 'Multimedia University (MMU)',
      degree: 'Bachelor of Computer Science (Data Science)',
      dateRange: '2019 - 2021',
      achievements: [
        /*"Graduated Magna Cum Laude with 3.8 GPA",
        "Dean's List all semesters",
        "President of Computer Science Club",*/
      ],
    },
  ],
};
